baseURL = "https://beta.leonmelein.nl/"
languageCode = "nl-nl"
DefaultContentLanguage = "nl"
title = "Léon"
theme = "leon2024"
summaryLength = 40
copyright = " © {year}"
[menu]
	[[menu.main]]
  	identifier = "nieuws"
	name = "Nieuws"
	title = "Nieuws"
	url = "/blog/"
	weight = -400
	[[menu.main]]
  	identifier = "project"
	name = "Projecten"
	title = "Projecten"
	url = "/project/"
	weight = -200
	[[menu.main]]
  	identifier = "about"
	name = "Over"
	title = "Over"
	url = "/about/"
	weight = -100
	[[menu.main]]
  	identifier = "contact"
	name = "Contact"
	title = "Contact"
	url = "/contact/"
	weight = 0
	[[menu.footer]]
  	identifier = "contact"
	name = "Contact"
	title = "Contact"
	url = "/contact/"
	weight = 0
[taxonomies]
	# Blog posts
	category = "categories"
  	tag = "tags"

  	# Portfolio
  	product = "products"
  	organization = "organizations"
  	state = "states"
  	partner = "partners"
[markup.goldmark.renderer]
    unsafe = true
