name = 'Léon (2024)'
license = 'MIT'
licenselink = 'https://github.com/leonmelein/.nl/LICENSE'
description = 'My Personal Brand theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/leonmelein/.nl'


# Taxonomy terms
tags = ['blog', 'personal', 'branding']
features = ['blog', 'portfolio']

# If the theme has multiple authors
authors = [
  {name = 'Léon Melein', homepage = 'https://www.leonmelein.nl'}
]
