name: Automatic deploy

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy with rsync
        run: rsync -avz ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/www/leonmelein

      # - name: Copy minimal (HTTP only) config
      #   uses: garygrossgarten/github-action-ssh@release		
      #   with:		
      #     command: sudo mv /www/leonmelein/conf/minimal.conf	/etc/nginx/conf.d/
      #     host: ${{ secrets.SSH_HOST }}		
      #     username: github-actions		
      #     privateKey: ${{ secrets.SSH_PRIVATE_KEY}}		

      - name: Restart nginx	
        uses: garygrossgarten/github-action-ssh@release		
        with:		
          command: sudo systemctl restart nginx	
          host: ${{ secrets.SSH_HOST }}		
          username: github-actions		
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}		

      - name: Request/reinstall certificate		
        uses: garygrossgarten/github-action-ssh@release		
        with:		
          command: sudo certbot --nginx -d ${{ secrets.URL }} -d www.${{ secrets.URL }} --keep --no-redirect		
          host: ${{ secrets.SSH_HOST }}		
          username: github-actions		
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}		

      # - name: Copy minimal (HTTPS only) config
      #   uses: garygrossgarten/github-action-ssh@release		
      #   with:		
      #     command: sudo mv /www/leonmelein/conf/full.conf	/etc/nginx/conf.d/
      #     host: ${{ secrets.SSH_HOST }}		
      #     username: github-actions		
      #     privateKey: ${{ secrets.SSH_PRIVATE_KEY}}		

      - name: Restart nginx	
        uses: garygrossgarten/github-action-ssh@release		
        with:		
          command: sudo systemctl restart nginx	
          host: ${{ secrets.SSH_HOST }}		
          username: github-actions		
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}		

